-- Script d'insertion des devises dans la table TBDEVISE
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('MAD', 504, 'Dirham marocain');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('DKK', 208, 'Couronne danoise');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('ZMW', 984, 'Kwacha de Zambie');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('AFN', 971, 'Afghani');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('ZAR', 710, 'Rand');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('ALL', 8, 'Lek');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('DZD', 12, 'Dinar algérien');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('EUR', 978, 'Euro');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('AOA', 973, 'Kwanza');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('XCD', 951, 'Dollar des Caraïbes orientales');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('ANG', 532, 'Florin des Antilles');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('SAR', 682, 'Riyal saoudien');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('ARS', 32, 'Peso argentin');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('AMD', 51, 'Dram armïnien');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('AWG', 533, 'Florin d`Aruba');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('AUD', 36, 'Dollar australien');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('AZN', 944, 'Manat');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('BSD', 44, 'Dollar des Bahamas');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('BHD', 48, 'Dinar de Bahreïn');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('BDT', 50, 'Taka');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('BBD', 52, 'Dollar de Barbade');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('BYR', 974, 'Rouble bélorusse');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('BZD', 84, 'Dollar de Belize');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('XOF', 952, 'Franc CFA - BCEAO');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('BMD', 60, 'Dollar des Bermudes');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('INR', 356, 'Roupie indienne (Ngultrum)');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('BOB', 68, 'Boliviano (Mvdol)');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('BAM', 977, 'Mark convertible');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('BWP', 72, 'Pula');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('NOK', 578, 'Couronne norvégienne');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('BRL', 986, 'Real de Brésil');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('BND', 96, 'Dollar de Brunei');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('BGN', 975, 'Lev de Bulgarie');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('BIF', 108, 'Franc du Burundi');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('KYD', 136, 'Dollar des Iles Caïmanes');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('KHR', 116, 'Riel');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('XAF', 950, 'Franc CFA - BEAC');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('CAD', 124, 'Dollar canadien');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('CVE', 132, 'Escudo du Cap-Vert');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('CLP', 152, 'Peso chilien (Unité d`investissement)');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('CNY', 156, 'Yuan Ren-Min-Bi');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('COP', 170, 'Peso colombien (Unidad de Valor Real)');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('KMF', 174, 'Franc des Comores');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('CDF', 976, 'Franc Congolais');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('NZD', 554, 'Dollar néerlandais');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('KRW', 410, 'Won');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('KPW', 408, 'Won de la Corée du Nord');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('CRC', 188, 'Colon de Costa Rica');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('HRK', 191, 'Kuna');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('CUP', 192, 'Peso cubain');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('DJF', 262, 'Franc de Djibouti');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('DOP', 214, 'Peso dominicain');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('EGP', 818, 'Livre Égyptienne');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('SVC', 222, 'Colon du El Salvador (Dollar des ï¿½tats-Unis)');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('AED', 784, 'Dirham des Émirats arabes unis');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('USD', 840, 'Dollar des États-Unis');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('ERN', 232, 'Nakfa');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('EEK', 233, 'Couronne estonienne');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('ETB', 230, 'Birr Éthiopien');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('FKP', 238, 'Livre de Falkland');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('FJD', 242, 'Dollar de Fidji');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('XDR', 960, 'Droit de tirage spécial (D.T.S.)');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('GMD', 270, 'Dalasi');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('GEL', 981, 'Lari');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('GHS', 936, 'Ghana Cedi');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('GIP', 292, 'Livre de Gibraltar');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('GTQ', 320, 'Quetzal');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('GBP', 826, 'Livre Sterling');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('GNF', 324, 'Franc guinéen');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('GWP', 624, 'Peso de Guinée-Bissau (Franc CFA - BCEAO)');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('GYD', 328, 'Dollar de Guyane');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('HTG', 332, 'Gourde (Dollar des États-Unis)');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('HNL', 340, 'Lempira');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('HKD', 344, 'Dollar de Hong-Kong');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('HUF', 348, 'Forint');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('IDR', 360, 'Rupiah');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('IRR', 364, 'Rial iranien');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('IQD', 368, 'Dinar iraquien');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('ISK', 352, 'Couronne islandaise');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('ILS', 376, 'Nouvel israïli sheqel');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('JMD', 388, 'Dollar jamaïcain');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('JPY', 392, 'Yen');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('JOD', 400, 'Dinar jordanien');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('KZT', 398, 'Tenge');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('KES', 404, 'Shilling du Kenya');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('KGS', 417, 'Som');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('KWD', 414, 'Dinar koweïtien');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('LAK', 418, 'Kip');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('LVL', 428, 'Lats letton');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('LBP', 422, 'Livre libanaise');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('LRD', 430, 'Dollar libérien');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('LYD', 434, 'Dinar libyen');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('CHF', 756, 'Franc suisse');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('LTL', 440, 'Litas lituanien');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('MOP', 446, 'Pataca');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('MKD', 807, 'Denar');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('MGA', 969, 'Malagasy Ariary');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('MYR', 458, 'Ringgit de Malaisie');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('MWK', 454, 'Kwacha de Malawi');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('MVR', 462, 'Rufiyaa');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('MUR', 480, 'Roupie de Maurice');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('MRO', 478, 'Ouguija');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('MXN', 484, 'Peso mexicain (Mexican Unidad de Inversion - UDI)');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('MDL', 498, 'Leu de Moldovie');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('MNT', 496, 'Tugrik');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('MZN', 943, 'Metical');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('MMK', 104, 'Kyat');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('NPR', 524, 'Roupie du Népal');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('NIO', 558, 'Cordoba Oro');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('NGN', 566, 'Naira');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('XPF', 953, 'Franc CFP');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('OMR', 512, 'Rial Omani');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('UGX', 800, 'Nouveau Shilling ougandais');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('UZS', 860, 'Soum d`Ouzbékistan');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('PKR', 586, 'Roupie du Pakistan');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('PAB', 590, 'Balboa (Dollar des États-Unis)');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('PGK', 598, 'Kina');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('PYG', 600, 'Guarani');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('PEN', 604, 'Nouveau Sol');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('PHP', 608, 'Peso philippin');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('PLN', 985, 'Zloty');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('QAR', 634, 'Riyal du Qatar');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('RON', 946, 'Nouveau Leu');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('RUB', 643, 'Rouble russe');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('RWF', 646, 'Franc du Rwanda');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('SHP', 654, 'Livre de Sainte-Hélène');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('SBD', 90, 'Dollar de Salomon');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('WST', 882, 'Tala');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('STD', 678, 'Dobra');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('RSD', 941, 'Dinar de Serbie');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('SCR', 690, 'Roupie des Seychelles');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('SLL', 694, 'Leone');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('SGD', 702, 'Dollar de Singapour');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('SKK', 703, 'Couronne slovaque');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('SOS', 706, 'Shilling de Somalie');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('SDG', 938, 'Livre soudanaise');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('LKR', 144, 'Roupie de Sri Lanka');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('SEK', 752, 'Couronne suédoise');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('SRD', 968, 'Dollar de Suriname');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('SZL', 748, 'Lilangeni');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('SYP', 760, 'Livre syrienne');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('TJS', 972, 'Somoni');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('TWD', 901, 'Nouveau dollar de Taïwan');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('TZS', 834, 'Shilling de Tanzanie');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('CZK', 203, 'Couronne tchèque');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('THB', 764, 'Baht');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('TOP', 776, 'Pa`anga');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('TTD', 780, 'Dollar de la Trinité et de Tobago');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('TND', 788, 'Dinar tunisien');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('TMM', 795, 'Manat');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('TRY', 949, 'Nouvelle Livre');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('UAH', 980, 'Hryvnia');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('UYI', 940, 'Peso uruguayen');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('VUV', 548, 'Vatu');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('VEF', 937, 'Bolivar Fuerte');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('VND', 704, 'Dong');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('YER', 886, 'Riyal du Yï¿½men');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('ZMK', 894, 'Kwacha de Zambie');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('ZWR', 935, 'Dollar du Zimbabwe');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('XAU', 959, 'Or');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('XBA', 955, 'Unité européenne composï¿½e (EURCO)');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('XBB', 956, 'Unité moétaire europï¿½enne (U.M.E.-6 monnaie)');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('XBC', 957, 'Unité de compte 9 (U.E.C.-9 monnaie)');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('XBD', 958, 'Unité de compte 17(U.E.C.-17 monnaie)');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('XPD', 964, 'Palladium');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('XPT', 962, 'Platine');
INSERT INTO C##MGSTGADR.TICDEVISE (CDALPHA, CDISO, LIBELE) VALUES ('XAG', 961, 'Argent');









-- Insertion des taux de change pour toutes les devises par rapport au MGA
-- Date fixe : 28/03/25
-- Taux approximatifs (� ajuster selon les cours r�els)

INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 504, 1); -- MAD = 1 MGA (� ajuster)
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 208, 700); -- DKK = 700 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 984, 0.2); -- ZMW = 0.2 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 971, 0.05); -- AFN = 0.05 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 710, 150); -- ZAR = 150 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 8, 50); -- ALL = 50 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 12, 35); -- DZD = 35 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 978, 5100); -- EUR = 5100 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 973, 10); -- AOA = 10 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 951, 1900); -- XCD = 1900 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 532, 2800); -- ANG = 2800 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 682, 1300); -- SAR = 1300 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 32, 5); -- ARS = 5 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 51, 12); -- AMD = 12 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 533, 2800); -- AWG = 2800 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 36, 3300); -- AUD = 3300 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 944, 300); -- AZN = 300 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 44, 4500); -- BSD = 4500 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 48, 12000); -- BHD = 12000 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 50, 40); -- BDT = 40 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 52, 2200); -- BBD = 2200 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 974, 150); -- BYR = 150 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 84, 2200); -- BZD = 2200 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 952, 7.5); -- XOF = 7.5 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 60, 4500); -- BMD = 4500 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 356, 55); -- INR = 55 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 68, 650); -- BOB = 650 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 977, 5100); -- BAM = 5100 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 72, 330); -- BWP = 330 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 578, 430); -- NOK = 430 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 986, 900); -- BRL = 900 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 96, 3300); -- BND = 3300 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 975, 5100); -- BGN = 5100 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 108, 1.5); -- BIF = 1.5 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 136, 5500); -- KYD = 5500 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 116, 1.1); -- KHR = 1.1 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 950, 7.5); -- XAF = 7.5 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 124, 3300); -- CAD = 3300 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 132, 45); -- CVE = 45 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 152, 5); -- CLP = 5 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 156, 620); -- CNY = 620 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 170, 1.1); -- COP = 1.1 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 174, 10); -- KMF = 10 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 976, 1.7); -- CDF = 1.7 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 554, 2700); -- NZD = 2700 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 410, 3.4); -- KRW = 3.4 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 408, 3.4); -- KPW = 3.4 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 188, 8.5); -- CRC = 8.5 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 191, 680); -- HRK = 680 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 192, 190); -- CUP = 190 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 262, 25); -- DJF = 25 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 214, 80); -- DOP = 80 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 818, 150); -- EGP = 150 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 222, 4500); -- SVC = 4500 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 784, 1220); -- AED = 1220 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 840, 4500); -- USD = 4500 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 232, 300); -- ERN = 300 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 233, 320); -- EEK = 320 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 230, 80); -- ETB = 80 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 238, 5700); -- FKP = 5700 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 242, 2000); -- FJD = 2000 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 960, 6000); -- XDR = 6000 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 270, 75); -- GMD = 75 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 981, 1700); -- GEL = 1700 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 936, 350); -- GHS = 350 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 292, 5700); -- GIP = 5700 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 320, 580); -- GTQ = 580 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 826, 5700); -- GBP = 5700 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 324, 5); -- GNF = 5 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 624, 7.5); -- GWP = 7.5 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 328, 21); -- GYD = 21 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 332, 4500); -- HTG = 4500 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 340, 180); -- HNL = 180 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 344, 575); -- HKD = 575 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 348, 12); -- HUF = 12 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 360, 0.28); -- IDR = 0.28 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 364, 0.11); -- IRR = 0.11 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 368, 3.5); -- IQD = 3.5 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 352, 32); -- ISK = 32 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 376, 1200); -- ILS = 1200 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 388, 29); -- JMD = 29 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 392, 30); -- JPY = 30 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 400, 6350); -- JOD = 6350 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 398, 10); -- KZT = 10 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 404, 35); -- KES = 35 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 417, 50); -- KGS = 50 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 414, 14600); -- KWD = 14600 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 418, 0.25); -- LAK = 0.25 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 428, 8100); -- LVL = 8100 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 422, 3); -- LBP = 3 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 430, 23); -- LRD = 23 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 434, 3500); -- LYD = 3500 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 756, 5000); -- CHF = 5000 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 440, 1650); -- LTL = 1650 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 446, 560); -- MOP = 560 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 807, 82); -- MKD = 82 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 969, 1); -- MGA = 1 MGA (devise de r�f�rence)
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 458, 950); -- MYR = 950 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 454, 2.7); -- MWK = 2.7 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 462, 290); -- MVR = 290 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 480, 100); -- MUR = 100 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 478, 13); -- MRO = 13 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 484, 270); -- MXN = 270 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 498, 250); -- MDL = 250 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 496, 1.3); -- MNT = 1.3 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 943, 70); -- MZN = 70 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 104, 2.1); -- MMK = 2.1 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 524, 34); -- NPR = 34 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 558, 160); -- NIO = 160 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 566, 3.5); -- NGN = 3.5 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 953, 38); -- XPF = 38 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 512, 11700); -- OMR = 11700 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 800, 1.2); -- UGX = 1.2 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 860, 0.35); -- UZS = 0.35 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 586, 16); -- PKR = 16 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 590, 4500); -- PAB = 4500 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 598, 1300); -- PGK = 1300 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 600, 0.6); -- PYG = 0.6 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 604, 1200); -- PEN = 1200 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 608, 80); -- PHP = 80 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 985, 1120); -- PLN = 1120 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 634, 1235); -- QAR = 1235 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 946, 1020); -- RON = 1020 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 643, 50); -- RUB = 50 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 646, 3.5); -- RWF = 3.5 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 654, 5700); -- SHP = 5700 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 90, 540); -- SBD = 540 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 882, 1700); -- WST = 1700 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 678, 0.2); -- STD = 0.2 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 941, 38); -- RSD = 38 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 690, 300); -- SCR = 300 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 694, 0.4); -- SLL = 0.4 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 702, 3300); -- SGD = 3300 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 703, 150); -- SKK = 150 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 706, 7.5); -- SOS = 7.5 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 938, 7.5); -- SDG = 7.5 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 144, 14); -- LKR = 14 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 752, 430); -- SEK = 430 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 968, 1200); -- SRD = 1200 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 748, 250); -- SZL = 250 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 760, 2); -- SYP = 2 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 972, 430); -- TJS = 430 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 901, 140); -- TWD = 140 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 834, 1.8); -- TZS = 1.8 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 203, 190); -- CZK = 190 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 764, 120); -- THB = 120 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 776, 1900); -- TOP = 1900 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 780, 660); -- TTD = 660 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 788, 1450); -- TND = 1450 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 795, 0.05); -- TMM = 0.05 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 949, 140); -- TRY = 140 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 980, 115); -- UAH = 115 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 940, 120); -- UYI = 120 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 548, 38); -- VUV = 38 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 937, 0.1); -- VEF = 0.1 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 704, 0.18); -- VND = 0.18 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 886, 18); -- YER = 18 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 894, 0.2); -- ZMK = 0.2 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 935, 0.0001); -- ZWR = 0.0001 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 959, 8500000); -- XAU = 8500000 MGA (or)
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 955, 5100); -- XBA = 5100 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 956, 5100); -- XBB = 5100 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 957, 5100); -- XBC = 5100 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 958, 5100); -- XBD = 5100 MGA
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 964, 5500000); -- XPD = 5500000 MGA (palladium)
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 962, 4500000); -- XPT = 4500000 MGA (platine)
INSERT INTO C##MGSTGADR.BKTAU (dco, dev, tind) VALUES (TO_DATE('28/03/25', 'DD/MM/YY'), 961, 55000); -- XAG = 55000 MGA (argent)
commit;
